public class FetchSlave {
/*
public String text{get; set;}   
public String text1{get; set;}
Integer i=0;
    public PageReference getSlave() {
        Check_Master__c m=[select Id from Check_Master__c where Name=:text];
        List <Check_SlaveA__c> sv=[select Name from Check_SlaveA__c where Check_Master__c =:m.Id ];
        for(i=0;i<sv.size();i++)
        {text1=sv[i].name;}         
        return null;
     }
*/
}